#!/bin/bash

echo "Launching Extensions Container..."

# Configure:
export MONGO_URL="mongodb://localhost:27017/micros"

# Cluster:
export CLUSTER_DISCOVERY_URL="mongodb://localhost:27017/micros"
export CLUSTER_ENDPOINT_URL="http://localhost:3001"
export CLUSTER_SERVICE="extensions"

meteor run --port 3001
